[2023-11-09T18:28:55.619+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_scraper.export manual__2023-11-09T17:19:26.510251+00:00 [queued]>
[2023-11-09T18:28:55.624+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_scraper.export manual__2023-11-09T17:19:26.510251+00:00 [queued]>
[2023-11-09T18:28:55.624+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-09T18:28:55.639+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): export> on 2023-11-09 17:19:26.510251+00:00
[2023-11-09T18:28:55.644+0000] {standard_task_runner.py:57} INFO - Started process 4147 to run task
[2023-11-09T18:28:55.646+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'query_scraper', 'export', 'manual__2023-11-09T17:19:26.510251+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag_definitions.py', '--cfg-path', '/tmp/tmpo67_kg6_']
[2023-11-09T18:28:55.648+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask export
[2023-11-09T18:28:55.673+0000] {task_command.py:415} INFO - Running <TaskInstance: query_scraper.export manual__2023-11-09T17:19:26.510251+00:00 [running]> on host bc76e66ea169
[2023-11-09T18:28:55.713+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='query_scraper' AIRFLOW_CTX_TASK_ID='export' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T17:19:26.510251+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-09T17:19:26.510251+00:00'
[2023-11-09T18:28:55.738+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task_definitions.py", line 148, in export
    df.to_excel(f'{output_path}/data_collected.xlsx')
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 2284, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/formats/excel.py", line 834, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 48, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2023-11-09T18:28:55.747+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=query_scraper, task_id=export, execution_date=20231109T171926, start_date=20231109T182855, end_date=20231109T182855
[2023-11-09T18:28:55.755+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task export (No module named 'openpyxl'; 4147)
[2023-11-09T18:28:55.777+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-09T18:28:55.788+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
