[2023-11-09T18:04:53.293+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_scraper.collect_items_specifications manual__2023-11-09T17:19:26.510251+00:00 [queued]>
[2023-11-09T18:04:53.299+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_scraper.collect_items_specifications manual__2023-11-09T17:19:26.510251+00:00 [queued]>
[2023-11-09T18:04:53.299+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 5
[2023-11-09T18:04:53.313+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): collect_items_specifications> on 2023-11-09 17:19:26.510251+00:00
[2023-11-09T18:04:53.318+0000] {standard_task_runner.py:57} INFO - Started process 2409 to run task
[2023-11-09T18:04:53.320+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'query_scraper', 'collect_items_specifications', 'manual__2023-11-09T17:19:26.510251+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag_definitions.py', '--cfg-path', '/tmp/tmpgh9fyurx']
[2023-11-09T18:04:53.322+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask collect_items_specifications
[2023-11-09T18:04:53.347+0000] {task_command.py:415} INFO - Running <TaskInstance: query_scraper.collect_items_specifications manual__2023-11-09T17:19:26.510251+00:00 [running]> on host bc76e66ea169
[2023-11-09T18:04:53.387+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='query_scraper' AIRFLOW_CTX_TASK_ID='collect_items_specifications' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T17:19:26.510251+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-09T17:19:26.510251+00:00'
[2023-11-09T18:04:53.410+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task_definitions.py", line 112, in scrape_specifications
    specs = self._scrape_specifications(df)
  File "/opt/airflow/dags/task_definitions.py", line 202, in _scrape_specifications
    specs = scraper.scrape(list(df['url']))
  File "/opt/airflow/dags/task_definitions.py", line 28, in scrape
    self.info(f'Number of urls to be requested: {len(urls)}')
  File "/opt/airflow/dags/resources/logger.py", line 18, in info
    self.logger.info(message, *args, **kw_args)
AttributeError: 'ScrapeSpecifications' object has no attribute 'logger'
[2023-11-09T18:04:53.417+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=query_scraper, task_id=collect_items_specifications, execution_date=20231109T171926, start_date=20231109T180453, end_date=20231109T180453
[2023-11-09T18:04:53.423+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task collect_items_specifications ('ScrapeSpecifications' object has no attribute 'logger'; 2409)
[2023-11-09T18:04:53.452+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-09T18:04:53.469+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
