[2023-11-09T18:01:17.660+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_scraper.collect_items_specifications manual__2023-11-09T17:19:26.510251+00:00 [queued]>
[2023-11-09T18:01:17.666+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_scraper.collect_items_specifications manual__2023-11-09T17:19:26.510251+00:00 [queued]>
[2023-11-09T18:01:17.666+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-09T18:01:17.681+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): collect_items_specifications> on 2023-11-09 17:19:26.510251+00:00
[2023-11-09T18:01:17.685+0000] {standard_task_runner.py:57} INFO - Started process 2324 to run task
[2023-11-09T18:01:17.687+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'query_scraper', 'collect_items_specifications', 'manual__2023-11-09T17:19:26.510251+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dag_definitions.py', '--cfg-path', '/tmp/tmp34u0frzb']
[2023-11-09T18:01:17.688+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask collect_items_specifications
[2023-11-09T18:01:17.716+0000] {task_command.py:415} INFO - Running <TaskInstance: query_scraper.collect_items_specifications manual__2023-11-09T17:19:26.510251+00:00 [running]> on host bc76e66ea169
[2023-11-09T18:01:17.756+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='query_scraper' AIRFLOW_CTX_TASK_ID='collect_items_specifications' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T17:19:26.510251+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-09T17:19:26.510251+00:00'
[2023-11-09T18:01:17.779+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task_definitions.py", line 110, in scrape_specifications
    specs = self._scrape_specifications(df)
  File "/opt/airflow/dags/task_definitions.py", line 199, in _scrape_specifications
    df['url'] = [scraper._handle_url(url) for url in df['url']]
  File "/opt/airflow/dags/task_definitions.py", line 199, in <listcomp>
    df['url'] = [scraper._handle_url(url) for url in df['url']]
  File "/opt/airflow/dags/task_definitions.py", line 19, in _handle_url
    if self.domain not in url:
AttributeError: type object 'ScrapeSpecifications' has no attribute 'domain'
[2023-11-09T18:01:17.784+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=query_scraper, task_id=collect_items_specifications, execution_date=20231109T171926, start_date=20231109T180117, end_date=20231109T180117
[2023-11-09T18:01:17.790+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task collect_items_specifications (type object 'ScrapeSpecifications' has no attribute 'domain'; 2324)
[2023-11-09T18:01:17.819+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-09T18:01:17.844+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
