[2023-11-09T17:40:09.652+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_scraper.collect_items manual__2023-11-09T17:19:26.510251+00:00 [queued]>
[2023-11-09T17:40:09.657+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_scraper.collect_items manual__2023-11-09T17:19:26.510251+00:00 [queued]>
[2023-11-09T17:40:09.657+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-11-09T17:40:09.673+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): collect_items> on 2023-11-09 17:19:26.510251+00:00
[2023-11-09T17:40:09.677+0000] {standard_task_runner.py:57} INFO - Started process 151 to run task
[2023-11-09T17:40:09.679+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'query_scraper', 'collect_items', 'manual__2023-11-09T17:19:26.510251+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_definitions.py', '--cfg-path', '/tmp/tmp54y2u43i']
[2023-11-09T17:40:09.680+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask collect_items
[2023-11-09T17:40:09.706+0000] {task_command.py:415} INFO - Running <TaskInstance: query_scraper.collect_items manual__2023-11-09T17:19:26.510251+00:00 [running]> on host 273cd10b3230
[2023-11-09T17:40:09.748+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='query_scraper' AIRFLOW_CTX_TASK_ID='collect_items' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T17:19:26.510251+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-09T17:19:26.510251+00:00'
[2023-11-09T17:40:09.770+0000] {logger.py:18} INFO - Searching query: BOLSA FEMININA TIRACOLO EM NAPA  
[2023-11-09T17:40:09.770+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task_definitions.py", line 97, in collect
    dfs.append(
NameError: name 'dfs' is not defined. Did you mean: 'df'?
[2023-11-09T17:40:09.776+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=query_scraper, task_id=collect_items, execution_date=20231109T171926, start_date=20231109T174009, end_date=20231109T174009
[2023-11-09T17:40:09.783+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task collect_items (name 'dfs' is not defined; 151)
[2023-11-09T17:40:09.811+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-09T17:40:09.837+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
